//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ShoppingCarts = new HashSet<ShoppingCart>();
            this.TransactionDetails = new HashSet<TransactionDetail>();
        }
    
        public int ProductID { get; set; }
        public string Name { get; set; }
        public int Qty { get; set; }
        public string Features { get; set; }
        public string Image { get; set; }
        public decimal Price { get; set; }
        public System.DateTime DateListed { get; set; }
        public int CategoryID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<ShoppingCart> ShoppingCarts { get; set; }
        public virtual ICollection<TransactionDetail> TransactionDetails { get; set; }
    }
}
